// Code generated by Kitex v0.3.2. DO NOT EDIT.

package authservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/jjeejj/Hertz-Kitex-Micro-Service-Template/kitex_gen/auth"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler auth.AuthService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
