// Code generated by Kitex v0.3.2. DO NOT EDIT.
package authservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/jjeejj/Hertz-Kitex-Micro-Service-Template/kitex_gen/auth"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler auth.AuthService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
