// Code generated by hertz generator.

package open_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/jjeejj/Hertz-Kitex-Micro-Service-Template/server/cmd/open_api/biz/model/server/cmd/open_api"
)

// GetToken .
// @router /token [POST]
func GetToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req open_api.GetTokenReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(open_api.GetTokenResp)

	c.JSON(consts.StatusOK, resp)
}
