// Code generated by Kitex v0.4.4. DO NOT EDIT.

package mqservice

import (
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	mq "github.com/jjeejj/Hertz-Kitex-Micro-Service-Template/kitex_gen/mq"
)

func serviceInfo() *kitex.ServiceInfo {
	return mqServiceServiceInfo
}

var mqServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "MqService"
	handlerType := (*mq.MqService)(nil)
	methods := map[string]kitex.MethodInfo{}
	extra := map[string]interface{}{
		"PackageName": "mq",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}
