// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

// @title open api
// @version 1.0
// @description 开放平台接口

// @contact.name jjeejj
// @contact.url https://github.com/jjeejj

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8888
// @BasePath /open
// @schemes http
func main() {
	h := server.New(
		server.WithBasePath("/api"),
	)

	register(h)
	h.Spin()
}
