// Code generated by Kitex v0.4.4. DO NOT EDIT.

package ossservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	oss "github.com/jjeejj/Hertz-Kitex-Micro-Service-Template/kitex_gen/oss"
)

func serviceInfo() *kitex.ServiceInfo {
	return ossServiceServiceInfo
}

var ossServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "OssService"
	handlerType := (*oss.OssService)(nil)
	methods := map[string]kitex.MethodInfo{
		"PreSignedPutObjectUrl": kitex.NewMethodInfo(preSignedPutObjectUrlHandler, newOssServicePreSignedPutObjectUrlArgs, newOssServicePreSignedPutObjectUrlResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "oss",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func preSignedPutObjectUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*oss.OssServicePreSignedPutObjectUrlArgs)
	realResult := result.(*oss.OssServicePreSignedPutObjectUrlResult)
	success, err := handler.(oss.OssService).PreSignedPutObjectUrl(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOssServicePreSignedPutObjectUrlArgs() interface{} {
	return oss.NewOssServicePreSignedPutObjectUrlArgs()
}

func newOssServicePreSignedPutObjectUrlResult() interface{} {
	return oss.NewOssServicePreSignedPutObjectUrlResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PreSignedPutObjectUrl(ctx context.Context, req *oss.PreSignedPutObjectUrlReq) (r *oss.PreSignedPutObjectUrlResp, err error) {
	var _args oss.OssServicePreSignedPutObjectUrlArgs
	_args.Req = req
	var _result oss.OssServicePreSignedPutObjectUrlResult
	if err = p.c.Call(ctx, "PreSignedPutObjectUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
