# 不同配置环境的 nacos 配置信息
local:
    host: 127.0.0.1
    port: 8848
    namespace: f550177d-aeca-4ddc-a0a6-9c2687fe0523
    user: 'nacos'
    password: 'nacos'
    weight: 0
dev:
    host: 127.0.0.1
    port: 8848
    namespace: f550177d-aeca-4ddc-a0a6-9c2687fe0523
    user: 'nacos'
    password: 'nacos'
    weight: 10
test:
    host: 127.0.0.1
    port: 8848
    namespace: 6e815bb4-25d0-4155-a1e0-6ec17a7ee600
    user: 'nacos'
    password: 'nacos'
    weight: 10
prod:
    host: 127.0.0.1
    port: 8848
    namespace: 6e815bb4-25d0-4155-a1e0-6ec17a7ee600
    user: 'nacos'
    password: 'nacos'
    weight: 10

