// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	open_api "github.com/jjeejj/Hertz-Kitex-Micro-Service-Template/server/cmd/open_api/biz/router/open_api"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	open_api.Register(r)
}
