// Code generated by hertz generator.

package OpenApi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettokenMw() []app.HandlerFunc {
	// your code...
	return nil
}
