basePath: /open
host: localhost:8888
info:
  contact:
    name: jjeejj
    url: https://github.com/jjeejj
  description: 开放平台接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: open api
  version: "1.0"
paths:
  /token:
    post:
      responses: {}
schemes:
- http
swagger: "2.0"
